name: nasa

services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile

    image: nasa-image
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nasa
      SPRING_DATASOURCE_USERNAME: nasa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6380
    depends_on:
      - db
      - redis
    networks:
      - nasaNetwork
  db: # postgres 컨테이너
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nasa
      POSTGRES_USER: nasa
      POSTGRES_PASSWORD: password
    networks:
      - nasaNetwork
  redis: # redis 컨테이너
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - nasaNetwork
  controller: # ngrinder 컨테이너
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    environment:
      NGRINDER_ADMIN_USERID: admin
      NGRINDER_ADMIN_PASSWORD: admin
    networks:
      - nasaNetwork
  agent:
    image: ngrinder/agent
    restart: always
    depends_on:
      - controller
    command:
      - 'controller:80'
    networks:
      - nasaNetwork



networks:
  nasaNetwork: {}

