spring:

  datasource:
    url: jdbc:postgresql://db:5433/nasa
    driver-class-name: org.postgresql.Driver
    username: nasa
    password: password
  mvc:
    format:
      date: yyyy-MM-dd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false # DB 커넥션 고갈 방지
  data:
    redis:
      port: 6380
      host: redis

# Swagger
springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    path: /swagger-ui
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

# server 에러 로그 설정
server:
  error:
    include-stacktrace: never