# db 설정
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username:

# Swagger
springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

jwt:
  secret:
    key: 'd'

# https://api.nasa.gov/
# GPmcLoxilFPdfbPPcPg2fSeHxnJOl3rCc0mwQ6JA
# https://api.nasa.gov/planetary/apod?api_key=GPmcLoxilFPdfbPPcPg2fSeHxnJOl3rCc0mwQ6JA
